Contact form Added: Mobile Version
habitoz/portofolio pull request #3
Opened 2023-05-10 15:00 UTC by habitoz

contact form added according to the design and requirement given so far.
the following files has been altered due to this change
     - index.html is altered to include the contact form and imputs given from the design
     - style.css file is also altered to include styles for the contact form section
     - new image added to the assets folder

2023-05-10 15:36 UTC, GedeonTS reviewed
# INVALID REVIEW REQUEST

Hi @habitoz , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
<Img src="https://media.giphy.com/media/11tVh1XRNAunYI/giphy.gif">
## Invalid Code Review Request

This milestone is a [pair-programming activity](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/3_contact_form.md#work-and-submission-mode), Kindly make sure to have contribution from your partner on this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-12 09:20 UTC, Shedrack-Sunday requested changes
Hello @habitoz        👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done well so far in the project,  However, there are a few you need to work on, to move to the next project. 💯

 
![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️   
- Nice UI 👍 

  
# Required Changes  🌵 

- [x] You made some impressive reviews in the comments, which I must say is a job well done. However, there are some which missed 

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-12 09:20 UTC, Shedrack-Sunday commented on styles.css
> +  text-align: center;
- [ ] Nice work you did there 👍 . However, based on project requirements, you're meant to use Flexbox to style this section. This is to test your skill using that technique, which is an industry best practice and gives you more flexibility 👍 

## Requirement:
![image](https://github.com/habitoz/portofolio/assets/50990925/7c84febd-8740-471e-b7ef-364b7d46add2)

2023-05-12 09:20 UTC, Shedrack-Sunday commented on index.html
> +                    </li>
- [ ] For this section, `Name` input should have `maxlength="30"` attribute.
- [ ] Message input has `maxlength="500"` attribute.
- These are necessary validations to keep your code professional

## Requirement :
![image](https://github.com/habitoz/portofolio/assets/50990925/332608f6-8540-4493-8005-b381b01f26ea)

2023-05-12 09:46 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @habitoz 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Good replication of Figma design ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a great summary ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 12:20 UTC, merged